health_check:
  uri: "/ping"
  delay: 60
  timeout: 60

docker_deploy_type: kubernetes

project_name: oauth2-proxy
project_team: insightsplatform@dynata.com
project_group: insightsplatform
project_container_port: 4180

ingress_type: internet-facing

secrets:
  ANSIBLE_SECRET: ansible_secret
  KC_HMAC_SECRET_KEY_HEX: "KC_HMAC_SECRET_KEY_HEX"
  KC_PRIVATE_KEY: "KC_PRIVATE_KEY"

envs:
