# This docker-compose file can be used to bring up an example instance of oauth2-proxy
# for manual testing and exploration of features.
# Alongside OAuth2-Proxy, this file also starts Dex to act as the identity provider,
# etcd for storage for Dex, nginx as a reverse proxy and other http services for upstreams
#
# This file is an extension of the main compose file and must be used with it
#    docker-compose -f docker-compose.yaml -f docker-compose-nginx.yaml <command>
# Alternatively:
#    make nginx-<command> (eg make nginx-up, make nginx-down)
#
# Access one of the following URLs to initiate a login flow:
#    - http://oauth2-proxy.localhost
#
# The OAuth2 Proxy itself is hosted at http://oauth2-proxy.oauth2-proxy.localhost
#
# Note, the above URLs should work with Chrome, but you may need to add hosts
# entries for other browsers
#    127.0.0.1 oauth2-proxy.localhost
#    127.0.0.1 oauth2-proxy.oauth2-proxy.localhost

version: '3.0'
services:
  nginx:
    container_name: nginx
    image: nginx:1.18
    ports:
      - 80:80/tcp
    hostname: nginx
    volumes:
      - "./nginx-keycloak-folio3.conf:/etc/nginx/conf.d/default.conf"
    networks:
      oauth2-proxy: {}
    depends_on:
      - oauth2-proxy
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:debug
    # security_opt:
    #   - seccomp:unconfined
    #   - apparmor=unconfined
    # cap_add: 
    #   - SYS_PTRACE
    # entrypoint: ['/bin/dlv', '--listen=:41800', '--headless=true', '--accept-multiclient', '--api-version=2', 'exec', '/bin/oauth2-proxy', '--continue', '--']
    # command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy-pe-env-nginx-keycloak-folio3.cfg:/oauth2-proxy.cfg"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - KC_HMAC_SECRET_KEY_HEX=${KC_HMAC_SECRET_KEY_HEX}
      - KC_PRIVATE_KEY=${KC_PRIVATE_KEY}
    restart: unless-stopped
    networks:
      oauth2-proxy:
        aliases:
          - oauth2-proxy.localhost
    ports:
      - 4180:4180/tcp
      - 41800:41800/tcp

networks:
  oauth2-proxy:
    external:
      name: pe